version: '3.9'
services:
  gateway:
    build:
      context: ./
    environment:
      LAMBDA_TARGET_URL: "http://hello-world-lambda:8080"
      PORT: "8080"
    ports:
      - "127.0.0.1:8080:8080"
  hello-world-lambda:
    build:
      context: examples/hello-world-with-vue3/lambda-rie
    ports:
      - "127.0.0.1:9090:8080"
